[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "clubconnect"
version = "0.0.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]